### PR TITLE
Feedback Changes

### PR DESCRIPTION
**Pull request by jSylvestre**
Increase default table size to 100 for List of clients

### CODE REVIEW

**Comment by jSylvestre** [comment]
image

**Comment by jSylvestre** [comment]
image

**Comment by jSylvestre** [comment]
image

**Comment by jSylvestre** [comment]
image

**Comment by jSylvestre** [comment]
image

**Comment by srkirkland** [comment]
@jSylvestre looks good -- maybe make the "please select dry matter test" for accurate quote part a little more visible, but otherwise looks great

**Comment by jSylvestre** [comment]
@srkirkland As a h2 instead of a p:

image

**Pull request merged**
