### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by benningd54**
PDF instructions for Wine Smoke Taint Clients.

### CODE REVIEW

**Review by jSylvestre — CHANGES_REQUESTED** [review]
@benningd54 Please move this to the pdf folder:
https://github.com/ucdavis/Anlab/tree/master/Anlab.Mvc/wwwroot/media/pdf

**Comment by benningd54** [comment]
Jason,

I believe that I am lost. :-/
Where is the pdf folder?
and
Now that I have the file in one folder, what's the easiest way of moving it?

-db

**Comment by jSylvestre** [comment]
@benningd54 I'm not sure how you would do it with your tools. For me it is just a drag and drop, then push the changes to github.
I've done that for you.
Just a FYI, I don't see that you are displaying this file anywhere yet.

I'll approve this in just a minute.

**Review by jSylvestre — APPROVED** [review]

**Comment by benningd54** [comment]
Thank you,

I'm sending a separate email about everything else...

-db

**Comment by jSylvestre** [comment]
This has been done in pr #842 instead

**Pull request closed without merging**
