### PR TITLE
Update contact.md

### PR DESCRIPTION
**Pull request by benningd54**
Update info on USPS and other carriers.

### CODE REVIEW

**Comment by jSylvestre** [comment]
image

**Comment by jSylvestre** [comment]
@benningd54 Blue is often something is clickable. Not sure if this is the correct style to use.

**Comment by benningd54** [comment]
What do you recommend?
We want it to stand out and be noticeable.

-db

**Comment by jSylvestre** [comment]
@benningd54 It is up to you. This is what your other PR looks like by removing the style and replacing the <p> tags with <strong> tags:

image

**Comment by benningd54** [comment]
Let's go without the blue.
But can you add a <br /> above "Campus Map"?

Thanks,
-db

**Comment by jSylvestre** [comment]
image

**Comment by benningd54** [comment]
I made those changes.
Once they finish building I’ll approve them.

Thanks,
-Jason

**Comment by benningd54** [comment]
I just looked and the changes have not shown up yet.
Am I supposed to do something more?

-db

**Comment by benningd54** [comment]
I approved them, but didn’t merge them.
If you click merge, it will automatically deploy to prod within 10 to 15 minutes

**Pull request merged**
