### PR TITLE
Design 7

### PR DESCRIPTION
**Pull request by cydoval**
LET ME INTO MASTERRRR

### CODE REVIEW

**Comment by srkirkland** [comment]
@jSylvestre When you get some time and all PRs have been merged, can you figure out how to fix these merge conflicts and then pull in cal's work?  Or maybe update master to this branch and have cal verify

**Comment by jSylvestre** [comment]
@srkirkland No idea what the form.scss should be in the merge conflict
The other two files I should be able to fix

**Comment by jSylvestre** [comment]
I'll fix the specs on Monday.

**Comment by jSylvestre** [comment]
@srkirkland Would it be better to wait for the other branches to be merged before this one? There will be some conflicts I think.

**Comment by srkirkland** [comment]
@cydoval sure we can wait until we get some of the current PRs in

**Comment by srkirkland** [comment]
@jSylvestre Oops sorry @cydoval I mean to tell jason we can wait for current PRs to merge before fixing and merging this.

**Pull request merged**
