### PR TITLE
Jcs/try to update emails

### PR DESCRIPTION
**Pull request by jSylvestre**

### CODE REVIEW

**Comment by jSylvestre** [comment]
image

**Comment by jSylvestre** [comment]
When I actually sent it, it looked like this in my email (missing extra space between <p>

image

**Comment by jSylvestre** [comment]
@srkirkland When I generated the email. it ended stripping out all the formatting.
We should look at replacing the emails for anlab...

**Review by srkirkland — APPROVED** [review]
changes seem ok.  And yes I agree it might be about time to change over the emails to something newer

**Pull request merged**
